### ISSUE TITLE
auth_forcepasswordchange is set, error "You cannot proceed without changing your password, however there is no available page for changing it."

### ISSUE THREAD

**Issue by steveatdmtd** [catalyst/moodle-auth_userkey#37] opened 2019-05-13 15:37 UTC
We are using auth_userkey on moodle 3.5 Linux (ubuntu) and it is working great. One issue that we are facing is that when a user on our site clicks on a link to the moodle site, the site successfully gets a token and logs in but when the user account is then created on that moodle site, "auth_forcepasswordchange" is set as a user preference which then results in an error message: "You cannot proceed without changing your password, however there is no available page for changing it.". Have you had other reports of this issue? Any recommendations on resolving ? One way to kind of hack past the issue is to edit several file on the moodle server that have "set_user_preference(‘auth_forcepasswordchange', 1, $user)" and hard code that to "set_user_preference(‘auth_forcepasswordchange', 0, $user)". I cannot find a moodle setting that turns off setting "auth_forcepasswordchange" to true in the mdl_user_preferences table. 

Ideas/recommendations would be super helpful and thank you so much in advance for any help you might be able to provide.

**Comment by dmitriim** [comment] 2019-05-16 21:58
Hi @steveatdmtd,

We didn't see someone reports this issue before. I was looking at the code and can't see why this could happen.

Are you sure that you are not using any other customisation that could set auth_forcepasswordchange to 1 for new users? Also can you be more specific about core line you changed to "hack" moodle to fix that? This can help me to track it down.

Also do you send a password when you request a token and create a user? 

Cheers,
Dmitrii

**Comment by dmitriim** [comment] 2019-05-16 23:43
By the way I wasn't able to replicate this issue using vanilla moodle 3.5.6 and the latest version of the plugin.

**Comment by dmitriim** [comment] 2019-05-26 21:41
@steveatdmtd can you please provide more info about how to replicate this issue?

**Comment by dmitriim** [comment] 2019-07-24 21:54
@steveatdmtd any chance you can provide more information?

**Comment by dmitriim** [comment] 2019-11-03 21:06
Closed as can't reproduce.

**Closed as completed** 2019-11-03 21:06 UTC
